version: "3.9"
services:
  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: air -c .air.toml
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - LDFLAGS=${LDFLAGS}
    volumes:
      - .:/app

#  redis:
#    image: redis
#    ports:
#      - 6379:${RE_PORT}
